name: shamiri
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  carbon_icons: ^0.0.1+2
  charts_flutter: ^0.12.0
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.0.0
  flutter_localizations:
    sdk: flutter
  google_fonts: 2.1.1
  intl: ^0.17.0
  package_info_plus: ^1.4.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.0
  flutter_launcher_icons: ^0.9.2

# launcher icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

# native splash screen Android & iOS
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#2e2e2e"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  fullscreen: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
